projectName: demo-project
groupId: com.yildizholding.ocean
artifactId: demo-project
packageName: com.example.demo
dependencies:
  - web
  - data-jpa
javaVersion: 17
springBootVersion: 3.4.4
outputPath: C:\\Users\\seraf\\Desktop\\passthroguh-projects\\